import type { Klaster, NamaIkon, Tahap } from "./tipe";

/** Petugas yang sedang masuk. Dipakai untuk jejak audit dan baris log. */
export const petugas = {
  nama: "Arif Setiawan",
  unit: "Diskominfo Kota Bandung",
  inisial: "AS",
};

export const TAHAP: { nama: string; ikon: NamaIkon }[] = [
  { nama: "Perlu verifikasi", ikon: "lingkaran" },
  { nama: "Diteruskan", ikon: "teruskan" },
  { nama: "Ditindaklanjuti", ikon: "proses" },
  { nama: "Selesai", ikon: "selesai" },
];

/** Satu langkah maju dari tiap tahap, dipakai tombol utama di panel periksa. */
export const LANJUT: { ke: Tahap; label: string; ikon: NamaIkon; catatan: string }[] = [
  {
    ke: 1,
    label: "Verifikasi dan teruskan",
    ikon: "verifikasi",
    catatan: "Laporan diverifikasi dan didisposisi ke instansi penanggung jawab",
  },
  {
    ke: 2,
    label: "Tandai ditindaklanjuti",
    ikon: "kerja",
    catatan: "Instansi menyatakan penanganan lapangan sedang berjalan",
  },
  {
    ke: 3,
    label: "Tandai selesai",
    ikon: "selesai",
    catatan: "Penanganan dinyatakan selesai oleh petugas",
  },
];

export const INSTANSI = [
  "Dinas Bina Marga dan Penataan Ruang",
  "Dinas Lingkungan Hidup dan Kebersihan",
  "Dinas Perhubungan",
  "Dinas Pekerjaan Umum",
  "DPKP3",
  "Satuan Polisi Pamong Praja",
];

/** Batas tindak lanjut yang berlaku di meja ini. */
export const BATAS_HARI_KERJA = 5;

/** Laporan masuk seluruh kanal, 14 hari sampai 16 Sep 2026. */
export const harian: [string, number][] = [
  ["Kam 3 Sep", 38],
  ["Jum 4 Sep", 52],
  ["Sab 5 Sep", 19],
  ["Min 6 Sep", 12],
  ["Sen 7 Sep", 41],
  ["Sel 8 Sep", 47],
  ["Rab 9 Sep", 36],
  ["Kam 10 Sep", 44],
  ["Jum 11 Sep", 58],
  ["Sab 12 Sep", 22],
  ["Min 13 Sep", 15],
  ["Sen 14 Sep", 61],
  ["Sel 15 Sep", 53],
  ["Rab 16 Sep", 47],
];

/**
 * Data contoh. Bukan laporan warga sungguhan: nama, NIK, dan nomor telepon
 * dikarang, koordinat menunjuk ke ruas jalan nyata di Kota Bandung.
 */
export const dataAwal: Klaster[] = [
  {
    id: "KLS-0031",
    kategori: "Jalan rusak dan berlubang",
    wilayah: "Sukajadi, Cicendo, Gedebage",
    instansi: "Dinas Bina Marga dan Penataan Ruang",
    ambang: 0.85,
    lapor: [
      {
        tiket: "TKT-260916-0473",
        tahap: 2,
        sisa: 2,
        ts: 2609161402,
        tgl: "16 Sep 2026",
        jam: "14:02",
        kanal: "WhatsApp bot",
        ringkas: "Lubang sedalam kira-kira 20 cm di jalur lambat depan gang",
        mentah:
          "pak jalan depan gang deket pvj bolong parah udah 2 minggu, tadi pagi ada motor jatuh",
        jalan: "Jl. Dr. Djunjunan, jalur lambat arah timur, dekat KM 2+300",
        kelurahan: "Sukabungah",
        kecamatan: "Sukajadi",
        koordinat: "-6.89213, 107.58761",
        skor: 0.91,
        foto: {
          nama: "IMG-20260916-140127.jpg",
          ukuran: "2,1 MB",
          gps: "-6.89347, 107.59904",
          selisih: "1,4 km",
        },
        pelapor: {
          nama: "Rangga N.",
          namaPenuh: "Rangga Nurhakim",
          nik: "3273••••••••0006",
          nikPenuh: "3273041709940006",
          wa: "+62 812-••••-4471",
          waPenuh: "+62 812-9033-4471",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          ["Ditindaklanjuti", "Regu tambal cepat dijadwalkan 17 Sep pagi", "16 Sep 16:40"],
          ["Diteruskan", "Disposisi ke Bidang Pemeliharaan Jalan", "16 Sep 15:12"],
          ["Perlu verifikasi", "Masuk lewat bot, dipetakan ke klaster KLS-0031", "16 Sep 14:02"],
        ],
      },
      {
        tiket: "TKT-260915-0388",
        tahap: 1,
        sisa: 4,
        ts: 2609151944,
        tgl: "15 Sep 2026",
        jam: "19:44",
        kanal: "WhatsApp bot",
        ringkas: "Aspal mengelupas sepanjang kira-kira 30 meter di jalur cepat",
        mentah:
          "aspal ngelupas panjang banget di soekarno hatta arah cibiru, bahaya buat motor malem",
        jalan: "Jl. Soekarno-Hatta arah timur, seberang Gedebage",
        kelurahan: "Cisaranten Kidul",
        kecamatan: "Gedebage",
        koordinat: "-6.94118, 107.69432",
        skor: 0.88,
        foto: {
          nama: "IMG-20260915-194402.jpg",
          ukuran: "1,7 MB",
          gps: "-6.94120, 107.69430",
          selisih: null,
        },
        pelapor: {
          nama: "Siti M.",
          namaPenuh: "Siti Maryani",
          nik: "3273••••••••0142",
          nikPenuh: "3273025508880142",
          wa: "+62 857-••••-1120",
          waPenuh: "+62 857-6644-1120",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          ["Diteruskan", "Disposisi ke Bidang Pemeliharaan Jalan", "16 Sep 08:10"],
          ["Perlu verifikasi", "Masuk lewat bot, dipetakan ke klaster KLS-0031", "15 Sep 19:44"],
        ],
      },
      {
        tiket: "TKT-260915-0359",
        tahap: 0,
        sisa: 3,
        ts: 2609151107,
        tgl: "15 Sep 2026",
        jam: "11:07",
        kanal: "WhatsApp bot",
        ringkas: "Bekas galian pipa belum dirapikan, permukaan bergelombang",
        mentah:
          "bekas galian pipa depan sekolah blm dirapihin, jadi gundukan, anak sekolah suka kepeleset",
        jalan: "Jl. Cihampelas, depan sekolah",
        kelurahan: "Cipaganti",
        kecamatan: "Coblong",
        koordinat: "-6.89055, 107.60402",
        skor: 0.72,
        foto: {
          nama: "IMG-20260915-110640.jpg",
          ukuran: "1,9 MB",
          gps: "-6.89052, 107.60399",
          selisih: null,
        },
        pelapor: {
          nama: "Wulan D.",
          namaPenuh: "Wulan Damayanti",
          nik: "3273••••••••0208",
          nikPenuh: "3273046201900208",
          wa: "+62 895-••••-3067",
          waPenuh: "+62 895-2214-3067",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          [
            "Perlu verifikasi",
            "Skor klasifikasi di bawah ambang klaster, perlu penilaian petugas",
            "15 Sep 11:07",
          ],
        ],
      },
      {
        tiket: "TKT-260914-0201",
        tahap: 3,
        sisa: null,
        ts: 2609140921,
        tgl: "14 Sep 2026",
        jam: "09:21",
        kanal: "Web",
        ringkas: "Lubang di mulut putaran balik sudah ditambal",
        mentah: "di puteran balik deket rs ada lubang gede, mobil sering kena",
        jalan: "Jl. Pasteur, putaran balik dekat rumah sakit",
        kelurahan: "Pasteur",
        kecamatan: "Sukajadi",
        koordinat: "-6.89902, 107.59015",
        skor: 0.84,
        foto: {
          nama: "unggahan-web-4412.jpg",
          ukuran: "980 KB",
          gps: "tidak ada EXIF",
          selisih: null,
        },
        pelapor: {
          nama: "Bayu P.",
          namaPenuh: "Bayu Prasetya",
          nik: "3273••••••••0033",
          nikPenuh: "3273011203910033",
          wa: "+62 811-••••-7781",
          waPenuh: "+62 811-2058-7781",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          ["Selesai", "Penambalan selesai, foto hasil diunggah petugas lapangan", "15 Sep 11:05"],
          ["Ditindaklanjuti", "Regu tambal cepat berangkat", "14 Sep 13:30"],
          ["Diteruskan", "Disposisi ke Bidang Pemeliharaan Jalan", "14 Sep 10:02"],
          ["Perlu verifikasi", "Masuk lewat web", "14 Sep 09:21"],
        ],
      },
    ],
  },
  {
    id: "KLS-0044",
    kategori: "Sampah menumpuk di TPS",
    wilayah: "Babakan Ciparay, Bandung Kulon",
    instansi: "Dinas Lingkungan Hidup dan Kebersihan",
    ambang: 0.88,
    lapor: [
      {
        tiket: "TKT-260916-0455",
        tahap: 0,
        sisa: -2,
        ts: 2609161137,
        tgl: "16 Sep 2026",
        jam: "11:37",
        kanal: "WhatsApp bot",
        ringkas: "Sampah meluber ke badan jalan, belum diangkut sejak akhir pekan",
        mentah: "tps deket pasar udah numpuk sampe jalan, bau banget dari sabtu belum diangkut",
        jalan: "Jl. Kopo, TPS samping pasar",
        kelurahan: "Babakan",
        kecamatan: "Babakan Ciparay",
        koordinat: "-6.94517, 107.58102",
        skor: 0.94,
        foto: {
          nama: "IMG-20260916-113701.jpg",
          ukuran: "3,0 MB",
          gps: "-6.94515, 107.58099",
          selisih: null,
        },
        pelapor: {
          nama: "Dewi R.",
          namaPenuh: "Dewi Rahmawati",
          nik: "3273••••••••0087",
          nikPenuh: "3273044411950087",
          wa: "+62 813-••••-2290",
          waPenuh: "+62 813-7712-2290",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          ["Perlu verifikasi", "Batas tindak lanjut 5 hari kerja terlampaui 2 hari", "16 Sep 11:37"],
        ],
      },
      {
        tiket: "TKT-260916-0448",
        tahap: 0,
        sisa: 3,
        ts: 2609160912,
        tgl: "16 Sep 2026",
        jam: "09:12",
        kanal: "WhatsApp bot",
        ringkas: "Gerobak sampah tidak datang tiga hari berturut-turut",
        mentah: "gerobak sampah ga dateng 3 hari, warga rt 04 udah numpuk di depan rumah",
        jalan: "Jl. Situ Aksan, RT 04 RW 09",
        kelurahan: "Cibuntu",
        kecamatan: "Bandung Kulon",
        koordinat: "-6.91744, 107.57388",
        skor: 0.79,
        foto: { nama: "tidak ada lampiran", ukuran: "-", gps: "-", selisih: null },
        pelapor: {
          nama: "Hendra S.",
          namaPenuh: "Hendra Saputra",
          nik: "3273••••••••0119",
          nikPenuh: "3273010806870119",
          wa: "+62 878-••••-6543",
          waPenuh: "+62 878-3391-6543",
          verif: "Belum terverifikasi",
        },
        riwayat: [["Perlu verifikasi", "Bot meminta foto, warga belum mengirim", "16 Sep 09:12"]],
      },
      {
        tiket: "TKT-260913-0311",
        tahap: 2,
        sisa: 1,
        ts: 2609131628,
        tgl: "13 Sep 2026",
        jam: "16:28",
        kanal: "WhatsApp bot",
        ringkas: "Bak sampah rusak sehingga sampah berserakan saat hujan",
        mentah: "bak sampahnya jebol, tiap hujan sampah kebawa air ke selokan",
        jalan: "Jl. Caringin, TPS pasar induk",
        kelurahan: "Babakan Ciparay",
        kecamatan: "Babakan Ciparay",
        koordinat: "-6.94820, 107.57611",
        skor: 0.9,
        foto: {
          nama: "IMG-20260913-162755.jpg",
          ukuran: "2,6 MB",
          gps: "-6.94818, 107.57608",
          selisih: null,
        },
        pelapor: {
          nama: "Asep K.",
          namaPenuh: "Asep Kurniawan",
          nik: "3273••••••••0176",
          nikPenuh: "3273010209830176",
          wa: "+62 821-••••-5512",
          waPenuh: "+62 821-4490-5512",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          ["Ditindaklanjuti", "Penggantian bak dijadwalkan pekan ini", "15 Sep 09:15"],
          ["Diteruskan", "Disposisi ke UPT Kebersihan Wilayah Barat", "14 Sep 08:40"],
          ["Perlu verifikasi", "Masuk lewat bot", "13 Sep 16:28"],
        ],
      },
    ],
  },
  {
    id: "KLS-0052",
    kategori: "Lampu penerangan jalan mati",
    wilayah: "Coblong, Cidadap",
    instansi: "Dinas Perhubungan",
    ambang: 0.8,
    lapor: [
      {
        tiket: "TKT-260915-0402",
        tahap: 1,
        sisa: 3,
        ts: 2609152108,
        tgl: "15 Sep 2026",
        jam: "21:08",
        kanal: "WhatsApp bot",
        ringkas: "Enam titik lampu padam di sepanjang tanjakan",
        mentah: "lampu jalan dago atas mati semua dari simpang sampe atas, gelap parah rawan",
        jalan: "Jl. Ir. H. Juanda atas, enam tiang antara simpang dan tikungan",
        kelurahan: "Dago",
        kecamatan: "Coblong",
        koordinat: "-6.86340, 107.61552",
        skor: 0.86,
        foto: {
          nama: "IMG-20260915-210812.jpg",
          ukuran: "1,2 MB",
          gps: "-6.86338, 107.61549",
          selisih: null,
        },
        pelapor: {
          nama: "Maya A.",
          namaPenuh: "Maya Anggraeni",
          nik: "3273••••••••0064",
          nikPenuh: "3273046302920064",
          wa: "+62 812-••••-8830",
          waPenuh: "+62 812-4417-8830",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          ["Diteruskan", "Disposisi ke UPT Penerangan Jalan Umum", "16 Sep 07:55"],
          ["Perlu verifikasi", "Masuk lewat bot", "15 Sep 21:08"],
        ],
      },
      {
        tiket: "TKT-260914-0333",
        tahap: 1,
        sisa: 2,
        ts: 2609142216,
        tgl: "14 Sep 2026",
        jam: "22:16",
        kanal: "WhatsApp bot",
        ringkas: "Lampu berkedip lalu padam di dua tiang dekat jembatan",
        mentah: "lampu deket jembatan kedap kedip terus mati, udah seminggu begitu",
        jalan: "Jl. Siliwangi, dua tiang dekat jembatan",
        kelurahan: "Lebak Siliwangi",
        kecamatan: "Coblong",
        koordinat: "-6.88712, 107.60894",
        skor: 0.83,
        foto: {
          nama: "IMG-20260914-221540.jpg",
          ukuran: "890 KB",
          gps: "-6.88710, 107.60890",
          selisih: null,
        },
        pelapor: {
          nama: "Fajar H.",
          namaPenuh: "Fajar Hidayat",
          nik: "3273••••••••0150",
          nikPenuh: "3273012811860150",
          wa: "+62 856-••••-7724",
          waPenuh: "+62 856-1187-7724",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          ["Diteruskan", "Disposisi ke UPT Penerangan Jalan Umum", "15 Sep 08:30"],
          ["Perlu verifikasi", "Masuk lewat bot", "14 Sep 22:16"],
        ],
      },
      {
        tiket: "TKT-260912-0244",
        tahap: 0,
        sisa: -1,
        ts: 2609122003,
        tgl: "12 Sep 2026",
        jam: "20:03",
        kanal: "Web",
        ringkas: "Tiang lampu miring dan kabel menjuntai ke trotoar",
        mentah: "tiang lampu miring, kabelnya ngegantung rendah banget di trotoar, bahaya kesetrum",
        jalan: "Jl. Ciumbuleuit, dekat pertigaan",
        kelurahan: "Hegarmanah",
        kecamatan: "Cidadap",
        koordinat: "-6.87205, 107.60310",
        skor: 0.74,
        foto: {
          nama: "unggahan-web-4377.jpg",
          ukuran: "1,4 MB",
          gps: "tidak ada EXIF",
          selisih: null,
        },
        pelapor: {
          nama: "Lina S.",
          namaPenuh: "Lina Suryani",
          nik: "3273••••••••0194",
          nikPenuh: "3273045704910194",
          wa: "+62 813-••••-9902",
          waPenuh: "+62 813-6650-9902",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          ["Perlu verifikasi", "Batas tindak lanjut 5 hari kerja terlampaui 1 hari", "12 Sep 20:03"],
        ],
      },
    ],
  },
  {
    id: "KLS-0058",
    kategori: "Saluran tersumbat dan genangan",
    wilayah: "Kiaracondong, Batununggal",
    instansi: "Dinas Pekerjaan Umum",
    ambang: 0.82,
    lapor: [
      {
        tiket: "TKT-260916-0431",
        tahap: 1,
        sisa: 4,
        ts: 2609160726,
        tgl: "16 Sep 2026",
        jam: "07:26",
        kanal: "WhatsApp bot",
        ringkas: "Genangan setinggi mata kaki bertahan lebih dari sehari",
        mentah:
          "got depan komplek mampet, air naik sampe mata kaki tiap hujan, udah sehari belum surut",
        jalan: "Jl. Ibrahim Adjie, depan gang komplek",
        kelurahan: "Babakan Surabaya",
        kecamatan: "Kiaracondong",
        koordinat: "-6.92210, 107.64418",
        skor: 0.85,
        foto: {
          nama: "IMG-20260916-072558.jpg",
          ukuran: "2,4 MB",
          gps: "-6.92208, 107.64420",
          selisih: null,
        },
        pelapor: {
          nama: "Teguh W.",
          namaPenuh: "Teguh Wibowo",
          nik: "3273••••••••0055",
          nikPenuh: "3273012310890055",
          wa: "+62 856-••••-3312",
          waPenuh: "+62 856-7028-3312",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          ["Diteruskan", "Disposisi ke Bidang Sumber Daya Air", "16 Sep 09:40"],
          ["Perlu verifikasi", "Masuk lewat bot", "16 Sep 07:26"],
        ],
      },
      {
        tiket: "TKT-260914-0296",
        tahap: 2,
        sisa: 0,
        ts: 2609141510,
        tgl: "14 Sep 2026",
        jam: "15:10",
        kanal: "WhatsApp bot",
        ringkas: "Mulut gorong-gorong tertutup endapan dan sampah",
        mentah: "gorong gorong ketutup lumpur sama sampah, kalo hujan air balik ke jalan",
        jalan: "Jl. Gatot Subroto, mulut gorong-gorong sisi utara",
        kelurahan: "Kacapiring",
        kecamatan: "Batununggal",
        koordinat: "-6.92044, 107.63091",
        skor: 0.87,
        foto: {
          nama: "IMG-20260914-150932.jpg",
          ukuran: "2,2 MB",
          gps: "-6.92041, 107.63088",
          selisih: null,
        },
        pelapor: {
          nama: "Rina O.",
          namaPenuh: "Rina Oktaviani",
          nik: "3273••••••••0163",
          nikPenuh: "3273044210900163",
          wa: "+62 878-••••-1188",
          waPenuh: "+62 878-5502-1188",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          ["Ditindaklanjuti", "Regu pengerukan dijadwalkan 17 Sep", "16 Sep 10:25"],
          ["Diteruskan", "Disposisi ke Bidang Sumber Daya Air", "15 Sep 08:05"],
          ["Perlu verifikasi", "Masuk lewat bot", "14 Sep 15:10"],
        ],
      },
    ],
  },
  {
    id: "KLS-0063",
    kategori: "Parkir liar di badan jalan",
    wilayah: "Andir, Cicendo",
    instansi: "Satuan Polisi Pamong Praja",
    ambang: 0.78,
    lapor: [
      {
        tiket: "TKT-260915-0371",
        tahap: 0,
        sisa: 1,
        ts: 2609151655,
        tgl: "15 Sep 2026",
        jam: "16:55",
        kanal: "Web",
        ringkas: "Mobil parkir dua lajur di depan pertokoan pada jam sibuk",
        mentah: "tiap sore mobil parkir dua baris depan ruko, jalan tinggal separo, macet sampe simpang",
        jalan: "Jl. Kebon Jati, depan deretan pertokoan",
        kelurahan: "Kebon Jeruk",
        kecamatan: "Andir",
        koordinat: "-6.91480, 107.60021",
        skor: 0.76,
        foto: {
          nama: "unggahan-web-4390.jpg",
          ukuran: "1,1 MB",
          gps: "tidak ada EXIF",
          selisih: null,
        },
        pelapor: {
          nama: "Ika F.",
          namaPenuh: "Ika Fitriani",
          nik: "3273••••••••0072",
          nikPenuh: "3273045012960072",
          wa: "+62 819-••••-4408",
          waPenuh: "+62 819-5523-4408",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          [
            "Perlu verifikasi",
            "Skor klasifikasi di bawah ambang klaster, perlu penilaian petugas",
            "15 Sep 16:55",
          ],
        ],
      },
      {
        tiket: "TKT-260913-0278",
        tahap: 1,
        sisa: 2,
        ts: 2609131822,
        tgl: "13 Sep 2026",
        jam: "18:22",
        kanal: "WhatsApp bot",
        ringkas: "Juru parkir memungut tarif di ruas larangan parkir",
        mentah: "ada jukir narik parkir padahal ada rambu dilarang parkir, tiap hari begitu",
        jalan: "Jl. Pajajaran, sisi selatan dekat rambu larangan",
        kelurahan: "Pasir Kaliki",
        kecamatan: "Cicendo",
        koordinat: "-6.90312, 107.59544",
        skor: 0.81,
        foto: {
          nama: "IMG-20260913-182102.jpg",
          ukuran: "1,5 MB",
          gps: "-6.90310, 107.59541",
          selisih: null,
        },
        pelapor: {
          nama: "Gilang R.",
          namaPenuh: "Gilang Ramadhan",
          nik: "3273••••••••0187",
          nikPenuh: "3273011506940187",
          wa: "+62 852-••••-3340",
          waPenuh: "+62 852-7719-3340",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          ["Diteruskan", "Disposisi ke Bidang Penegakan Perda dan Dishub", "14 Sep 09:12"],
          ["Perlu verifikasi", "Masuk lewat bot", "13 Sep 18:22"],
        ],
      },
    ],
  },
  {
    id: "KLS-0067",
    kategori: "Pohon tumbang dan dahan rawan",
    wilayah: "Antapani, Arcamanik",
    instansi: "DPKP3",
    ambang: 0.86,
    lapor: [
      {
        tiket: "TKT-260914-0288",
        tahap: 3,
        sisa: null,
        ts: 2609141812,
        tgl: "14 Sep 2026",
        jam: "18:12",
        kanal: "WhatsApp bot",
        ringkas: "Dahan besar menimpa trotoar, sudah dipangkas petugas",
        mentah: "dahan gede patah nutupin trotoar depan taman, orang jalan mesti turun ke jalan",
        jalan: "Jl. Terusan Jakarta, trotoar sisi taman",
        kelurahan: "Antapani Kidul",
        kecamatan: "Antapani",
        koordinat: "-6.91027, 107.65880",
        skor: 0.93,
        foto: {
          nama: "IMG-20260914-181204.jpg",
          ukuran: "2,8 MB",
          gps: "-6.91025, 107.65877",
          selisih: null,
        },
        pelapor: {
          nama: "Nurul H.",
          namaPenuh: "Nurul Hasanah",
          nik: "3273••••••••0091",
          nikPenuh: "3273046607930091",
          wa: "+62 852-••••-9075",
          waPenuh: "+62 852-1164-9075",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          ["Selesai", "Pemangkasan selesai, trotoar dibersihkan", "15 Sep 10:20"],
          ["Ditindaklanjuti", "Regu pemangkasan diberangkatkan", "14 Sep 19:45"],
          ["Diteruskan", "Disposisi ke Bidang Pertamanan", "14 Sep 18:50"],
          ["Perlu verifikasi", "Masuk lewat bot", "14 Sep 18:12"],
        ],
      },
      {
        tiket: "TKT-260916-0468",
        tahap: 0,
        sisa: 5,
        ts: 2609161318,
        tgl: "16 Sep 2026",
        jam: "13:18",
        kanal: "WhatsApp bot",
        ringkas: "Pohon miring ke arah rumah warga setelah angin kencang",
        mentah: "pohon di pinggir jalan miring ke rumah warga abis angin kenceng kemaren, takut roboh",
        jalan: "Jl. Cisaranten Kulon, bahu jalan sisi timur",
        kelurahan: "Cisaranten Kulon",
        kecamatan: "Arcamanik",
        koordinat: "-6.91544, 107.68122",
        skor: 0.89,
        foto: {
          nama: "IMG-20260916-131705.jpg",
          ukuran: "2,5 MB",
          gps: "-6.91540, 107.68119",
          selisih: null,
        },
        pelapor: {
          nama: "Yusuf A.",
          namaPenuh: "Yusuf Abdillah",
          nik: "3273••••••••0211",
          nikPenuh: "3273010703920211",
          wa: "+62 811-••••-4408",
          waPenuh: "+62 811-7736-4408",
          verif: "Terverifikasi NIK",
        },
        riwayat: [
          [
            "Perlu verifikasi",
            "Masuk lewat bot, ditandai berisiko oleh petugas piket",
            "16 Sep 13:18",
          ],
        ],
      },
    ],
  },
];
